# Generated by Django 2.1.2 on 2018-12-12 11:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('testcore', '0002_testexecution_report_status'),
    ]

    operations = [
        migrations.AddField(
            model_name='application',
            name='ready',
            field=models.BooleanField(default=False),
        ),
    ]
