# Generated by Django 2.1.2 on 2018-11-22 10:28

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('testcore', '0004_testparameter'),
    ]

    operations = [
        migrations.AlterField(
            model_name='testparameter',
            name='test',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='parameters', to='testcore.TestExecution'),
        ),
    ]
