# Generated by Django 2.1.1 on 2018-09-19 06:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('testcore', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='application',
            name='description',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='applicationtest',
            name='description',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='library',
            name='command',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='library',
            name='description',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='testexecution',
            name='reportText',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='testtype',
            name='description',
            field=models.TextField(blank=True, null=True),
        ),
    ]
